// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chorcha-ui/Aura.tsx": () => import("../components/mockups/chorcha-ui/Aura.tsx"),
  "./components/mockups/chorcha-ui/Blade.tsx": () => import("../components/mockups/chorcha-ui/Blade.tsx"),
  "./components/mockups/chorcha-ui/Nova.tsx": () => import("../components/mockups/chorcha-ui/Nova.tsx")
};
